import './global.css' 
import type { Metadata } from 'next'
import { IBM_Plex_Sans_Arabic } from 'next/font/google'
import logoTab from '../public/logoTab.svg'



export const metadata: Metadata = {
  title: 'UX Studio',
  description: 'Generated by create next app',
  icons: [{ rel: 'icon', url: logoTab.src }],
}
const ibm = IBM_Plex_Sans_Arabic({
  subsets: ['arabic'],
  weight: '400'
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ar" dir='rtl' >
      <body className={`${ibm.className} container`} >{children}</body>
    </html>
  )
}
